/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef FILTER_BAKE_CONFIG_H
#define FILTER_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <flecs.h>
#include <flecs_components_meta.h>
#include <flecs_json.h>

/* Headers of private dependencies */
#ifdef FILTER_IMPL
/* No dependencies */
#endif

/* Convenience macro for exporting symbols */
#ifndef FILTER_STATIC
  #if FILTER_IMPL && (defined(_MSC_VER) || defined(__MINGW32__))
    #define FILTER_API __declspec(dllexport)
  #elif FILTER_IMPL
    #define FILTER_API __attribute__((__visibility__("default")))
  #elif defined _MSC_VER
    #define FILTER_API __declspec(dllimport)
  #else
    #define FILTER_API
  #endif
#else
  #define FILTER_API
#endif

#endif

